repos:
  - repo: local
    hooks:
      - id: lint
        name: lint files
        entry: make lint
        language: system
        types: [python]
        stages: [commit]

      - id: test
        name: run tests
        entry: make test
        language: system
        stages: [push]

      - id: requirements
        name: generate requirements
        entry: .hooks/requirements.sh
        language: script
        files: "^Pipfile$"
        stages: [commit]

  - repo: https://github.com/python/black
    rev: stable
    hooks:
      - id: black
        name: format files
